name: foodapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  geolocator: ^14.0.1
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  path: ^1.9.1
  video_player: ^2.9.5
  file_picker: ^10.1.9
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  fl_chart: ^1.0.0
  sqflite: ^2.4.2
  connectivity_plus: ^6.1.4
  http: ^1.4.0
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" 
  adaptive_icon_background: "#00695C" 